// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://alhgqswqnklgjlmnnstn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsaGdxc3dxbmtsZ2psbW5uc3RuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMDA2NjAsImV4cCI6MjA1NjU3NjY2MH0.WUaDuIBWniJCih9Wl0C_n7CIUL5zWdkNOTXXynZS4DE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);